import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import {ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import {Toaster} from "sonner";
import ExitModal from "@/components/modals/exit-modal";
import HeartsModal from "@/components/modals/hearts-modal";
import PracticeModal from "@/components/modals/practice-modal";
import Head from "next/head";

const font = Nunito({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Lingo: Your own language teacher!",
    description: "Generated by create next app",
    icons: '/favicon.ico'
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <Head>
                <title>Lingo: Your own language teacher!</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <html lang="en">
            <body className={font.className}>
            <Toaster/>
            <ExitModal/>
            <HeartsModal/>
            <PracticeModal/>
            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}
